# Site settings
title: Mike Bochenek's Blog
email: mike@bochenek.ca
description: "technical learnings, writing practice, random thoughts, funny pics, photographs"
baseurl: "/blog"
url: "http://www.bochenek.ch"

excerpt_separator: "\n\n"


# Build settings
markdown: kramdown
permalink: pretty
